# Generated by Django 3.1.7 on 2021-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('cep', models.IntegerField()),
                ('rua', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('cpf', models.IntegerField()),
                ('pis', models.IntegerField()),
                ('senha', models.IntegerField()),
            ],
        ),
    ]
