# Generated by Django 3.1.7 on 2021-03-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios_fotos'),
        ),
    ]
